### PR TITLE
Don't fail when secrets missing

### PR DESCRIPTION
**Pull request by fydai**

### CODE REVIEW

**Comment by dkess** [comment]
We still shouldn't be failing silently here. As I see it, there are three cases:

* User specifies secrets, and they don't exist. Fail loudly
* User specifies secrets and they do exist. Carry on
* User doesn't specify secrets at all. Do nothing

This PR will make the first case fail silently, which is bad for debugging.

**Comment by fydai** [comment]
What makes this a bit more complicated is there are two other cases:
- Jenkins looks for a secrets file for the given app, and it doesn't exist. Carry on.
- Jenkins looks for a secrets file for the given app, and it does exist. Carry on.

**Comment by dkess** [comment]
Hmmm, I guess it'll fail anyways if the templates are using variables that aren't defined. Maybe print a message saying "no secrets found" or something, to make the log clearer?

**Comment by fydai** [comment]
Ninja'd by 3 seconds :P

**Pull request merged**
