### PR TITLE
python2 -> python3 migration

### PR DESCRIPTION
**Pull request by douglaslwong**
@matthew-mcallister merging into master for testing

### CODE REVIEW

**Comment by chriskuehl** [comment]
seems okay otherwise, i didn't test them or read too thoroughly though

**Comment by matthew-mcallister** [comment]
Check out `pyrc.find_emu_sessions`. We don't need to check if the python version is >= 3. If you wanted, you could additionally change it to use `subprocess.check_output` instead of `Popen`.

Also, get rid of the comment that says "Requires python >= 2.6".

**Comment by douglaslwong** [comment]
oops should've closed this PR last night, thanks for the feedbacks

**Comment by douglaslwong** [comment]
changes finalized and tested, @matthew-mcallister or @chriskuehl?

**Pull request merged**
