### PR TITLE
makevm: use predictable network interface names

### PR DESCRIPTION
**Pull request by matthew-mcallister**
Since we currently install stretch on new VMs, there should be no trouble merging.

### CODE REVIEW

**Comment by jvperrin** [comment]
Nice, looks good to me, maybe it could support jessie too if it looked for anything starting with `eth` too, since that won't happen with systems interface names?

**Comment by matthew-mcallister** [comment]
It could, I figured it just wouldn't get used much/ever---code minimalism, you know. Do you think it would be helpful?

**Comment by chriskuehl** [comment]
nice, lgtm

if you *do* care about jessie, it's probably as simple as changing `iface.startswith('en')` to `iface.startswith(('en', 'eth'))`

**Comment by matthew-mcallister** [comment]
Yep, I'm just being stubborn.

**Comment by jvperrin** [comment]
Fair enough, well if we need to support any new jessie VMs, at least it's an easy change with this.

**Pull request merged**
